package org.leafframework.data.dao.orm;

// Generated 2016-2-18 15:41:01 by Hibernate Tools 3.4.0.CR1

/**
 * Apartmentmgr generated by hbm2java
 */
public class Apartmentmgr implements java.io.Serializable {

	private Integer id;
	private String apartId;
	private String name;
	private String phone;
	private String description;

	public Apartmentmgr() {
	}

	public Apartmentmgr(String apartId, String name) {
		this.apartId = apartId;
		this.name = name;
	}

	public Apartmentmgr(String apartId, String name, String phone,
			String description) {
		this.apartId = apartId;
		this.name = name;
		this.phone = phone;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getApartId() {
		return this.apartId;
	}

	public void setApartId(String apartId) {
		this.apartId = apartId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
