package org.leafframework.data.dao.orm;

// Generated 2016-2-17 17:18:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Checkattend generated by hbm2java
 */
public class Checkattend implements java.io.Serializable {

	private int id;
	private String staffId;
	private String staffName;
	private String apartment;
	private String post;
	private Date checkdate;
	private String isCheck;

	public Checkattend() {
	}

	public Checkattend(int id, String staffId, String staffName) {
		this.id = id;
		this.staffId = staffId;
		this.staffName = staffName;
	}

	public Checkattend(int id, String staffId, String staffName,
			String apartment, String post, Date checkdate, String isCheck) {
		this.id = id;
		this.staffId = staffId;
		this.staffName = staffName;
		this.apartment = apartment;
		this.post = post;
		this.checkdate = checkdate;
		this.isCheck = isCheck;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	public String getApartment() {
		return this.apartment;
	}

	public void setApartment(String apartment) {
		this.apartment = apartment;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public Date getCheckdate() {
		return this.checkdate;
	}

	public void setCheckdate(Date checkdate) {
		this.checkdate = checkdate;
	}

	public String getIsCheck() {
		return this.isCheck;
	}

	public void setIsCheck(String isCheck) {
		this.isCheck = isCheck;
	}

}
