package org.leafframework.data.dao.orm;

// Generated 2016-2-23 15:13:15 by Hibernate Tools 3.4.0.CR1

/**
 * Month generated by hbm2java
 */
public class Month implements java.io.Serializable {

	private Integer id;
	private String monthId;
	private String monthName;

	public Month() {
	}

	public Month(String monthId, String monthName) {
		this.monthId = monthId;
		this.monthName = monthName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMonthId() {
		return this.monthId;
	}

	public void setMonthId(String monthId) {
		this.monthId = monthId;
	}

	public String getMonthName() {
		return this.monthName;
	}

	public void setMonthName(String monthName) {
		this.monthName = monthName;
	}

}
