package org.leafframework.data.dao.orm;

// Generated 2016-2-3 11:24:16 by Hibernate Tools 3.4.0.CR1

/**
 * Record generated by hbm2java
 */
public class Record implements java.io.Serializable {

	private int id;
	private String name;
	private int staffId;
	private String staffName;
	private String content;
	private String rewardPunish;
	private String career;

	public Record() {
	}

	public Record(int id, String name, int staffId, String staffName) {
		this.id = id;
		this.name = name;
		this.staffId = staffId;
		this.staffName = staffName;
	}

	public Record(int id, String name, int staffId, String staffName,
			String content, String rewardPunish, String career) {
		this.id = id;
		this.name = name;
		this.staffId = staffId;
		this.staffName = staffName;
		this.content = content;
		this.rewardPunish = rewardPunish;
		this.career = career;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getRewardPunish() {
		return this.rewardPunish;
	}

	public void setRewardPunish(String rewardPunish) {
		this.rewardPunish = rewardPunish;
	}

	public String getCareer() {
		return this.career;
	}

	public void setCareer(String career) {
		this.career = career;
	}

}
