package org.leafframework.data.dao.orm;

// Generated 2016-2-3 11:24:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Salarymgr generated by hbm2java
 */
public class Salarymgr implements java.io.Serializable {

	private int staffId;
	private String staffName;
	private String state;
	private String post;
	private Date inputtime;
	private String workage;
	private String salarypush;
	private String salarydetail;

	public Salarymgr() {
	}

	public Salarymgr(int staffId, String staffName) {
		this.staffId = staffId;
		this.staffName = staffName;
	}

	public Salarymgr(int staffId, String staffName, String state, String post,
			Date inputtime, String workage, String salarypush,
			String salarydetail) {
		this.staffId = staffId;
		this.staffName = staffName;
		this.state = state;
		this.post = post;
		this.inputtime = inputtime;
		this.workage = workage;
		this.salarypush = salarypush;
		this.salarydetail = salarydetail;
	}

	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public Date getInputtime() {
		return this.inputtime;
	}

	public void setInputtime(Date inputtime) {
		this.inputtime = inputtime;
	}

	public String getWorkage() {
		return this.workage;
	}

	public void setWorkage(String workage) {
		this.workage = workage;
	}

	public String getSalarypush() {
		return this.salarypush;
	}

	public void setSalarypush(String salarypush) {
		this.salarypush = salarypush;
	}

	public String getSalarydetail() {
		return this.salarydetail;
	}

	public void setSalarydetail(String salarydetail) {
		this.salarydetail = salarydetail;
	}

}
