package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TCRegisterSmscode generated by hbm2java
 */
public class TCRegisterSmscode implements java.io.Serializable {

	private Integer id;
	private String phone;
	private String regicode;
	private Date sendtime;

	public TCRegisterSmscode() {
	}

	public TCRegisterSmscode(String phone, String regicode, Date sendtime) {
		this.phone = phone;
		this.regicode = regicode;
		this.sendtime = sendtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRegicode() {
		return this.regicode;
	}

	public void setRegicode(String regicode) {
		this.regicode = regicode;
	}

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

}
