package org.leafframework.data.dao.orm;

// Generated 2015-12-14 16:20:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TCStaffgroupRela generated by hbm2java
 */
public class TCStaffgroupRela implements java.io.Serializable {

	private Integer id;
	private String staffId;
	private int groupId;
	private Date createTime;
	private Date updateTime;

	public TCStaffgroupRela() {
	}

	public TCStaffgroupRela(String staffId, int groupId, Date createTime) {
		this.staffId = staffId;
		this.groupId = groupId;
		this.createTime = createTime;
	}

	public TCStaffgroupRela(String staffId, int groupId, Date createTime,
			Date updateTime) {
		this.staffId = staffId;
		this.groupId = groupId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
