package org.leafframework.data.dao.orm;

// Generated 2015-12-14 16:20:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TCStaffgroup generated by hbm2java
 */
public class TCStaffgroup implements java.io.Serializable {

	private Integer id;
	private String groupName;
	private String cityId;
	private String remark;
	private Date createTime;
	private Date updateTime;

	public TCStaffgroup() {
	}

	public TCStaffgroup(String groupName, String cityId, Date createTime) {
		this.groupName = groupName;
		this.cityId = cityId;
		this.createTime = createTime;
	}

	public TCStaffgroup(String groupName, String cityId, String remark,
			Date createTime, Date updateTime) {
		this.groupName = groupName;
		this.cityId = cityId;
		this.remark = remark;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
