package org.leafframework.data.dao.orm;
// Generated 2014-11-8 21:08:30 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TLMain generated by hbm2java
 */
public class TLMain implements java.io.Serializable {

	private Integer id;
	private String logType;
	private String optrType;
	private String optrName;
	private int optrStaffId;
	private Date optrTime;
	private String remark;

	public TLMain() {
	}

	public TLMain(String logType, String optrType, String optrName,
			int optrStaffId, Date optrTime, String remark) {
		this.logType = logType;
		this.optrType = optrType;
		this.optrName = optrName;
		this.optrStaffId = optrStaffId;
		this.optrTime = optrTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}
	public String getOptrType() {
		return this.optrType;
	}

	public void setOptrType(String optrType) {
		this.optrType = optrType;
	}
	public String getOptrName() {
		return this.optrName;
	}

	public void setOptrName(String optrName) {
		this.optrName = optrName;
	}
	public int getOptrStaffId() {
		return this.optrStaffId;
	}

	public void setOptrStaffId(int optrStaffId) {
		this.optrStaffId = optrStaffId;
	}
	public Date getOptrTime() {
		return this.optrTime;
	}

	public void setOptrTime(Date optrTime) {
		this.optrTime = optrTime;
	}
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
