package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TLMenus generated by hbm2java
 */
public class TLMenus implements java.io.Serializable {

	private Integer id;
	private int logId;
	private int dirId;
	private String name;
	private String lvlId;
	private String icon;
	private Integer parentId;
	private String modifyTag;
	private String updateStaffId;
	private Date updateTime;

	public TLMenus() {
	}

	public TLMenus(int logId, int dirId, String icon, String modifyTag) {
		this.logId = logId;
		this.dirId = dirId;
		this.icon = icon;
		this.modifyTag = modifyTag;
	}

	public TLMenus(int logId, int dirId, String name, String lvlId, String icon, Integer parentId, String modifyTag, String updateStaffId,
			Date updateTime) {
		this.logId = logId;
		this.dirId = dirId;
		this.name = name;
		this.lvlId = lvlId;
		this.icon = icon;
		this.parentId = parentId;
		this.modifyTag = modifyTag;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	public int getDirId() {
		return this.dirId;
	}

	public void setDirId(int dirId) {
		this.dirId = dirId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLvlId() {
		return this.lvlId;
	}

	public void setLvlId(String lvlId) {
		this.lvlId = lvlId;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getModifyTag() {
		return this.modifyTag;
	}

	public void setModifyTag(String modifyTag) {
		this.modifyTag = modifyTag;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
