package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TLModules generated by hbm2java
 */
public class TLModules implements java.io.Serializable {

	private Integer id;
	private int logId;
	private int moduleId;
	private String name;
	private String subsystem;
	private String module;
	private String type;
	private String remark;
	private String url;
	private String icon;
	private Integer menuId;
	private String isUse;
	private String modifyTag;
	private String updateStaffId;
	private Date updateTime;

	public TLModules() {
	}

	public TLModules(int logId, int moduleId, String subsystem, String module, String icon, String isUse, String modifyTag,
			String updateStaffId, Date updateTime) {
		this.logId = logId;
		this.moduleId = moduleId;
		this.subsystem = subsystem;
		this.module = module;
		this.icon = icon;
		this.isUse = isUse;
		this.modifyTag = modifyTag;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public TLModules(int logId, int moduleId, String name, String subsystem, String module, String type, String remark, String url,
			String icon, Integer menuId, String isUse, String modifyTag, String updateStaffId, Date updateTime) {
		this.logId = logId;
		this.moduleId = moduleId;
		this.name = name;
		this.subsystem = subsystem;
		this.module = module;
		this.type = type;
		this.remark = remark;
		this.url = url;
		this.icon = icon;
		this.menuId = menuId;
		this.isUse = isUse;
		this.modifyTag = modifyTag;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubsystem() {
		return this.subsystem;
	}

	public void setSubsystem(String subsystem) {
		this.subsystem = subsystem;
	}

	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String getIsUse() {
		return this.isUse;
	}

	public void setIsUse(String isUse) {
		this.isUse = isUse;
	}

	public String getModifyTag() {
		return this.modifyTag;
	}

	public void setModifyTag(String modifyTag) {
		this.modifyTag = modifyTag;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
