package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TLRoleModule generated by hbm2java
 */
public class TLRoleModule implements java.io.Serializable {

	private Integer id;
	private int logId;
	private int relId;
	private Integer moduleId;
	private Integer roleId;
	private String modifyTag;
	private String remark;
	private String updateStaffId;
	private Date updateTime;

	public TLRoleModule() {
	}

	public TLRoleModule(int logId, int relId, String modifyTag, String updateStaffId, Date updateTime) {
		this.logId = logId;
		this.relId = relId;
		this.modifyTag = modifyTag;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public TLRoleModule(int logId, int relId, Integer moduleId, Integer roleId, String modifyTag, String remark, String updateStaffId,
			Date updateTime) {
		this.logId = logId;
		this.relId = relId;
		this.moduleId = moduleId;
		this.roleId = roleId;
		this.modifyTag = modifyTag;
		this.remark = remark;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	public int getRelId() {
		return this.relId;
	}

	public void setRelId(int relId) {
		this.relId = relId;
	}

	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getModifyTag() {
		return this.modifyTag;
	}

	public void setModifyTag(String modifyTag) {
		this.modifyTag = modifyTag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
