package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TLRoles generated by hbm2java
 */
public class TLRoles implements java.io.Serializable {

	private Integer id;
	private int logId;
	private int roleId;
	private String departCode;
	private String name;
	private String lvlId;
	private int parentId;
	private String modifyTag;
	private String remark;
	private String updateStaffId;
	private Date updateTime;

	public TLRoles() {
	}

	public TLRoles(int logId, int roleId, String lvlId, int parentId, String modifyTag, String updateStaffId, Date updateTime) {
		this.logId = logId;
		this.roleId = roleId;
		this.lvlId = lvlId;
		this.parentId = parentId;
		this.modifyTag = modifyTag;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public TLRoles(int logId, int roleId, String departCode, String name, String lvlId, int parentId, String modifyTag, String remark,
			String updateStaffId, Date updateTime) {
		this.logId = logId;
		this.roleId = roleId;
		this.departCode = departCode;
		this.name = name;
		this.lvlId = lvlId;
		this.parentId = parentId;
		this.modifyTag = modifyTag;
		this.remark = remark;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getDepartCode() {
		return this.departCode;
	}

	public void setDepartCode(String departCode) {
		this.departCode = departCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLvlId() {
		return this.lvlId;
	}

	public void setLvlId(String lvlId) {
		this.lvlId = lvlId;
	}

	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public String getModifyTag() {
		return this.modifyTag;
	}

	public void setModifyTag(String modifyTag) {
		this.modifyTag = modifyTag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
