package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TMailLogs generated by hbm2java
 */
public class TMailLogs implements java.io.Serializable {

	private Integer id;
	private int mailId;
	private String custEmail;
	private String status;
	private String operaStaffId;
	private Date operaTime;

	public TMailLogs() {
	}

	public TMailLogs(int mailId, String custEmail, String status, String operaStaffId, Date operaTime) {
		this.mailId = mailId;
		this.custEmail = custEmail;
		this.status = status;
		this.operaStaffId = operaStaffId;
		this.operaTime = operaTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getMailId() {
		return this.mailId;
	}

	public void setMailId(int mailId) {
		this.mailId = mailId;
	}

	public String getCustEmail() {
		return this.custEmail;
	}

	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getOperaStaffId() {
		return this.operaStaffId;
	}

	public void setOperaStaffId(String operaStaffId) {
		this.operaStaffId = operaStaffId;
	}

	public Date getOperaTime() {
		return this.operaTime;
	}

	public void setOperaTime(Date operaTime) {
		this.operaTime = operaTime;
	}

}
