package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TMailDetail generated by hbm2java
 */
public class TMailDetail implements java.io.Serializable {

	private Integer id;
	private String linkId;
	private String mailType;
	private int custId;
	private String custEmail;
	private String mailStatus;
	private Date createTime;

	public TMailDetail() {
	}

	public TMailDetail(String linkId, String mailType, int custId, String custEmail, String mailStatus, Date createTime) {
		this.linkId = linkId;
		this.mailType = mailType;
		this.custId = custId;
		this.custEmail = custEmail;
		this.mailStatus = mailStatus;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLinkId() {
		return this.linkId;
	}

	public void setLinkId(String linkId) {
		this.linkId = linkId;
	}

	public String getMailType() {
		return this.mailType;
	}

	public void setMailType(String mailType) {
		this.mailType = mailType;
	}

	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	public String getCustEmail() {
		return this.custEmail;
	}

	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	public String getMailStatus() {
		return this.mailStatus;
	}

	public void setMailStatus(String mailStatus) {
		this.mailStatus = mailStatus;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
