package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

/**
 * TMailTemplet generated by hbm2java
 */
public class TMailTemplet implements java.io.Serializable {

	private Integer id;
	private String mailType;
	private String mailTemplet;
	private String isMail;

	public TMailTemplet() {
	}

	public TMailTemplet(String mailType, String mailTemplet, String isMail) {
		this.mailType = mailType;
		this.mailTemplet = mailTemplet;
		this.isMail = isMail;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMailType() {
		return this.mailType;
	}

	public void setMailType(String mailType) {
		this.mailType = mailType;
	}

	public String getMailTemplet() {
		return this.mailTemplet;
	}

	public void setMailTemplet(String mailTemplet) {
		this.mailTemplet = mailTemplet;
	}

	public String getIsMail() {
		return this.isMail;
	}

	public void setIsMail(String isMail) {
		this.isMail = isMail;
	}

}
