package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TMArea generated by hbm2java
 */
public class TMArea implements java.io.Serializable {

	private Integer id;
	private String code;
	private String name;
	private String lvlId;
	private Integer parentId;
	private Integer pos;
	private String remark;
	private String updateStaffId;
	private Date updateTime;

	public TMArea() {
	}

	public TMArea(String code, String updateStaffId, Date updateTime) {
		this.code = code;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public TMArea(String code, String name, String lvlId, Integer parentId, Integer pos, String remark, String updateStaffId, Date updateTime) {
		this.code = code;
		this.name = name;
		this.lvlId = lvlId;
		this.parentId = parentId;
		this.pos = pos;
		this.remark = remark;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLvlId() {
		return this.lvlId;
	}

	public void setLvlId(String lvlId) {
		this.lvlId = lvlId;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getPos() {
		return pos;
	}

	public void setPos(Integer pos) {
		this.pos = pos;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
