package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TMMenus generated by hbm2java
 */
public class TMMenus implements java.io.Serializable {

	private Integer id;
	private String name;
	private String lvlId;
	private String icon;
	private int pos;
	private Integer parentId;
	private String updateStaffId;
	private Date updateTime;

	public TMMenus() {
	}

	public TMMenus(String icon, int pos) {
		this.icon = icon;
		this.pos = pos;
	}

	public TMMenus(String name, String lvlId, String icon, int pos, Integer parentId, String updateStaffId, Date updateTime) {
		this.name = name;
		this.lvlId = lvlId;
		this.icon = icon;
		this.pos = pos;
		this.parentId = parentId;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLvlId() {
		return this.lvlId;
	}

	public void setLvlId(String lvlId) {
		this.lvlId = lvlId;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public int getPos() {
		return this.pos;
	}

	public void setPos(int pos) {
		this.pos = pos;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
