package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TMModules generated by hbm2java
 */
public class TMModules implements java.io.Serializable {

	private Integer id;
	private String name;
	private String subsystem;
	private String module;
	private String type;
	private String remark;
	private String url;
	private String icon;
	private int pos;
	private String isUse;
	private Integer menuId;
	private String updateStaffId;
	private Date updateTime;

	public TMModules() {
	}

	public TMModules(String subsystem, String module, String icon, int pos, String isUse, String updateStaffId, Date updateTime) {
		this.subsystem = subsystem;
		this.module = module;
		this.icon = icon;
		this.pos = pos;
		this.isUse = isUse;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public TMModules(String name, String subsystem, String module, String type, String remark, String url, String icon, int pos,
			String isUse, Integer menuId, String updateStaffId, Date updateTime) {
		this.name = name;
		this.subsystem = subsystem;
		this.module = module;
		this.type = type;
		this.remark = remark;
		this.url = url;
		this.icon = icon;
		this.pos = pos;
		this.isUse = isUse;
		this.menuId = menuId;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubsystem() {
		return this.subsystem;
	}

	public void setSubsystem(String subsystem) {
		this.subsystem = subsystem;
	}

	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public int getPos() {
		return this.pos;
	}

	public void setPos(int pos) {
		this.pos = pos;
	}

	public String getIsUse() {
		return this.isUse;
	}

	public void setIsUse(String isUse) {
		this.isUse = isUse;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
