package org.leafframework.data.dao.orm;

// Generated 2015-7-21 14:43:12 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TMRoles generated by hbm2java
 */
public class TMRoles implements java.io.Serializable {

	private Integer id;
	private String name;
	private String lvlId;
	private int parentId;
	private String remark;
	private String updateStaffId;
	private Date updateTime;

	public TMRoles() {
	}

	public TMRoles(String lvlId, int parentId, String updateStaffId,
			Date updateTime) {
		this.lvlId = lvlId;
		this.parentId = parentId;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public TMRoles(String name, String lvlId, int parentId, String remark,
			String updateStaffId, Date updateTime) {
		this.name = name;
		this.lvlId = lvlId;
		this.parentId = parentId;
		this.remark = remark;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLvlId() {
		return this.lvlId;
	}

	public void setLvlId(String lvlId) {
		this.lvlId = lvlId;
	}

	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
