package org.leafframework.data.dao.orm;

// Generated 2015-7-8 20:06:55 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TMRoleModule generated by hbm2java
 */
public class TMRoleModule implements java.io.Serializable {

	private Integer id;
	private Integer roleId;
	private Integer moduleId;
	private String remark;
	private String updateStaffId;
	private Date updateTime;

	public TMRoleModule() {
	}

	public TMRoleModule(String updateStaffId, Date updateTime) {
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public TMRoleModule(Integer roleId, Integer moduleId, String remark, String updateStaffId, Date updateTime) {
		this.roleId = roleId;
		this.moduleId = moduleId;
		this.remark = remark;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(String updateStaffId) {
		this.updateStaffId = updateStaffId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
