package org.leafframework.data.dao.orm;

// Generated 2015-12-21 11:08:53 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TOAssignRule generated by hbm2java
 */
public class TOAssignRule implements java.io.Serializable {

	private Integer id;
	private String custType;
	private int custGroupId;
	private String goodsType;
	private String areaType;
	private String areaId;
	private Integer priority;
	private String sendType;
	private String selfGetArea;
	private String payType;
	private String recvType;
	private String recvAreaId;
	private int recvGroupId;
	private String remark;
	private Date createTime;
	private Date updateTime;

	public TOAssignRule() {
	}

	public TOAssignRule(String custType, int custGroupId, String goodsType, String areaId, String sendType, String payType,
			String recvType, String recvAreaId, int recvGroupId, Date createTime) {
		this.custType = custType;
		this.custGroupId = custGroupId;
		this.goodsType = goodsType;
		this.areaId = areaId;
		this.sendType = sendType;
		this.payType = payType;
		this.recvType = recvType;
		this.recvAreaId = recvAreaId;
		this.recvGroupId = recvGroupId;
		this.createTime = createTime;
	}

	public TOAssignRule(String custType, int custGroupId, String goodsType, String areaType, String areaId, Integer priority,
			String sendType, String selfGetArea, String payType, String recvType, String recvAreaId, int recvGroupId, String remark,
			Date createTime, Date updateTime) {
		this.custType = custType;
		this.custGroupId = custGroupId;
		this.goodsType = goodsType;
		this.areaType = areaType;
		this.areaId = areaId;
		this.priority = priority;
		this.sendType = sendType;
		this.selfGetArea = selfGetArea;
		this.payType = payType;
		this.recvType = recvType;
		this.recvAreaId = recvAreaId;
		this.recvGroupId = recvGroupId;
		this.remark = remark;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCustType() {
		return this.custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

	public int getCustGroupId() {
		return this.custGroupId;
	}

	public void setCustGroupId(int custGroupId) {
		this.custGroupId = custGroupId;
	}

	public String getGoodsType() {
		return this.goodsType;
	}

	public void setGoodsType(String goodsType) {
		this.goodsType = goodsType;
	}

	public String getAreaType() {
		return this.areaType;
	}

	public void setAreaType(String areaType) {
		this.areaType = areaType;
	}

	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getSendType() {
		return this.sendType;
	}

	public void setSendType(String sendType) {
		this.sendType = sendType;
	}

	public String getSelfGetArea() {
		return this.selfGetArea;
	}

	public void setSelfGetArea(String selfGetArea) {
		this.selfGetArea = selfGetArea;
	}

	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public String getRecvType() {
		return this.recvType;
	}

	public void setRecvType(String recvType) {
		this.recvType = recvType;
	}

	public String getRecvAreaId() {
		return this.recvAreaId;
	}

	public void setRecvAreaId(String recvAreaId) {
		this.recvAreaId = recvAreaId;
	}

	public int getRecvGroupId() {
		return this.recvGroupId;
	}

	public void setRecvGroupId(int recvGroupId) {
		this.recvGroupId = recvGroupId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
