package org.leafframework.data.dao.orm;

// Generated 2015-12-14 16:20:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TOAssignlog generated by hbm2java
 */
public class TOAssignlog implements java.io.Serializable {

	private Integer id;
	private int orderId;
	private String receiveGroup;
	private int useruleId;
	private String operateStaff;
	private Date createTime;
	private Date updateTime;
	private String remark;

	public TOAssignlog() {
	}

	public TOAssignlog(int orderId, String receiveGroup, int useruleId,
			String operateStaff, Date createTime) {
		this.orderId = orderId;
		this.receiveGroup = receiveGroup;
		this.useruleId = useruleId;
		this.operateStaff = operateStaff;
		this.createTime = createTime;
	}

	public TOAssignlog(int orderId, String receiveGroup, int useruleId,
			String operateStaff, Date createTime, Date updateTime, String remark) {
		this.orderId = orderId;
		this.receiveGroup = receiveGroup;
		this.useruleId = useruleId;
		this.operateStaff = operateStaff;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public String getReceiveGroup() {
		return this.receiveGroup;
	}

	public void setReceiveGroup(String receiveGroup) {
		this.receiveGroup = receiveGroup;
	}

	public int getUseruleId() {
		return this.useruleId;
	}

	public void setUseruleId(int useruleId) {
		this.useruleId = useruleId;
	}

	public String getOperateStaff() {
		return this.operateStaff;
	}

	public void setOperateStaff(String operateStaff) {
		this.operateStaff = operateStaff;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
