package org.leafframework.data.dao.orm;

// Generated 2015-12-14 16:20:40 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TOAssignResult generated by hbm2java
 */
public class TOAssignResult implements java.io.Serializable {

	private Integer id;
	private int orderId;
	private int groupId;
	private Date createTime;
	private Date updateTime;
	private String remark;

	public TOAssignResult() {
	}

	public TOAssignResult(int orderId, int groupId, Date createTime) {
		this.orderId = orderId;
		this.groupId = groupId;
		this.createTime = createTime;
	}

	public TOAssignResult(int orderId, int groupId, Date createTime,
			Date updateTime, String remark) {
		this.orderId = orderId;
		this.groupId = groupId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
