package org.leafframework.data.dao.orm;
// Generated 2014-11-8 21:08:30 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TOMain generated by hbm2java
 */
public class TOMain implements java.io.Serializable {

	private Integer id;
	private String orderType;
	private int acceptStaffId;
	private Date acceptTime;
	private String state;
	private int stateStaffId;
	private Date stateTime;
	private String remark;

	public TOMain() {
	}

	public TOMain(String orderType, int acceptStaffId, Date acceptTime,
			String state, int stateStaffId, Date stateTime, String remark) {
		this.orderType = orderType;
		this.acceptStaffId = acceptStaffId;
		this.acceptTime = acceptTime;
		this.state = state;
		this.stateStaffId = stateStaffId;
		this.stateTime = stateTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}
	public int getAcceptStaffId() {
		return this.acceptStaffId;
	}

	public void setAcceptStaffId(int acceptStaffId) {
		this.acceptStaffId = acceptStaffId;
	}
	public Date getAcceptTime() {
		return this.acceptTime;
	}

	public void setAcceptTime(Date acceptTime) {
		this.acceptTime = acceptTime;
	}
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	public int getStateStaffId() {
		return this.stateStaffId;
	}

	public void setStateStaffId(int stateStaffId) {
		this.stateStaffId = stateStaffId;
	}
	public Date getStateTime() {
		return this.stateTime;
	}

	public void setStateTime(Date stateTime) {
		this.stateTime = stateTime;
	}
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
