package org.leafframework.data.dao.orm;
// Generated 2014-11-8 21:08:30 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TOStatehis generated by hbm2java
 */
public class TOStatehis implements java.io.Serializable {

	private Integer id;
	private int orderId;
	private String state;
	private int staffId;
	private Date startTime;
	private Date endTime;
	private Date updateTime;
	private String remark;

	public TOStatehis() {
	}

	public TOStatehis(int orderId, String state, int staffId, Date startTime,
			Date endTime, Date updateTime, String remark) {
		this.orderId = orderId;
		this.state = state;
		this.staffId = staffId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
