package org.leafframework.data.dao.orm;
// Generated 2014-11-8 21:08:30 by Hibernate Tools 4.3.1

/**
 * TSMetadataColumn generated by hbm2java
 */
public class TSMetadataColumn implements java.io.Serializable {

	private Integer id;
	private String owner;
	private String tableName;
	private short columnId;
	private String columnName;
	private String label;
	private String dataDefault;
	private String dataType;
	private short dataLength;
	private String nullable;
	private String disabled;
	private String visible;
	private String remark;

	public TSMetadataColumn() {
	}

	public TSMetadataColumn(String owner, String tableName, short columnId,
			String columnName, String label, String dataType, short dataLength,
			String nullable, String disabled, String visible) {
		this.owner = owner;
		this.tableName = tableName;
		this.columnId = columnId;
		this.columnName = columnName;
		this.label = label;
		this.dataType = dataType;
		this.dataLength = dataLength;
		this.nullable = nullable;
		this.disabled = disabled;
		this.visible = visible;
	}
	public TSMetadataColumn(String owner, String tableName, short columnId,
			String columnName, String label, String dataDefault,
			String dataType, short dataLength, String nullable,
			String disabled, String visible, String remark) {
		this.owner = owner;
		this.tableName = tableName;
		this.columnId = columnId;
		this.columnName = columnName;
		this.label = label;
		this.dataDefault = dataDefault;
		this.dataType = dataType;
		this.dataLength = dataLength;
		this.nullable = nullable;
		this.disabled = disabled;
		this.visible = visible;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public short getColumnId() {
		return this.columnId;
	}

	public void setColumnId(short columnId) {
		this.columnId = columnId;
	}
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}
	public String getDataDefault() {
		return this.dataDefault;
	}

	public void setDataDefault(String dataDefault) {
		this.dataDefault = dataDefault;
	}
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}
	public short getDataLength() {
		return this.dataLength;
	}

	public void setDataLength(short dataLength) {
		this.dataLength = dataLength;
	}
	public String getNullable() {
		return this.nullable;
	}

	public void setNullable(String nullable) {
		this.nullable = nullable;
	}
	public String getDisabled() {
		return this.disabled;
	}

	public void setDisabled(String disabled) {
		this.disabled = disabled;
	}
	public String getVisible() {
		return this.visible;
	}

	public void setVisible(String visible) {
		this.visible = visible;
	}
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
