package org.leafframework.data.dao.orm;
// Generated 2014-11-8 21:08:30 by Hibernate Tools 4.3.1

/**
 * TSMetadataTable generated by hbm2java
 */
public class TSMetadataTable implements java.io.Serializable {

	private Integer id;
	private String owner;
	private String tableName;
	private String label;
	private String remark;

	public TSMetadataTable() {
	}

	public TSMetadataTable(String owner, String tableName, String label,
			String remark) {
		this.owner = owner;
		this.tableName = tableName;
		this.label = label;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
