package org.leafframework.data.dao.orm;
// Generated 2014-11-8 21:08:30 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TSOstate generated by hbm2java
 */
public class TSOstate implements java.io.Serializable {

	private Integer id;
	private String state;
	private String stateName;
	private String seq;
	private String orderType;
	private int updateStaffId;
	private Date updateTime;

	public TSOstate() {
	}

	public TSOstate(String state, String stateName, String seq,
			String orderType, int updateStaffId, Date updateTime) {
		this.state = state;
		this.stateName = stateName;
		this.seq = seq;
		this.orderType = orderType;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}
	public int getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(int updateStaffId) {
		this.updateStaffId = updateStaffId;
	}
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
