package org.leafframework.data.dao.orm;
// Generated 2014-11-8 21:08:30 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TSOtype generated by hbm2java
 */
public class TSOtype implements java.io.Serializable {

	private Integer id;
	private String orderType;
	private String orderTypeName;
	private String orderFlag;
	private int updateStaffId;
	private Date updateTime;

	public TSOtype() {
	}

	public TSOtype(String orderType, String orderTypeName, String orderFlag,
			int updateStaffId, Date updateTime) {
		this.orderType = orderType;
		this.orderTypeName = orderTypeName;
		this.orderFlag = orderFlag;
		this.updateStaffId = updateStaffId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}
	public String getOrderTypeName() {
		return this.orderTypeName;
	}

	public void setOrderTypeName(String orderTypeName) {
		this.orderTypeName = orderTypeName;
	}
	public String getOrderFlag() {
		return this.orderFlag;
	}

	public void setOrderFlag(String orderFlag) {
		this.orderFlag = orderFlag;
	}
	public int getUpdateStaffId() {
		return this.updateStaffId;
	}

	public void setUpdateStaffId(int updateStaffId) {
		this.updateStaffId = updateStaffId;
	}
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
