package org.leafframework.data.dao.orm;

// Generated 2016-2-3 10:40:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSTempIdCard generated by hbm2java
 */
public class TSTempIdCard implements java.io.Serializable {

	private Integer id;
	private String photoUpUrl;
	private String photoDownUrl;
	private String photoInHandUrl;
	private String uuid;
	private Date createTime;

	public TSTempIdCard() {
	}

	public TSTempIdCard(String photoUpUrl, String photoDownUrl,
			String photoInHandUrl, String uuid, Date createTime) {
		this.photoUpUrl = photoUpUrl;
		this.photoDownUrl = photoDownUrl;
		this.photoInHandUrl = photoInHandUrl;
		this.uuid = uuid;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPhotoUpUrl() {
		return this.photoUpUrl;
	}

	public void setPhotoUpUrl(String photoUpUrl) {
		this.photoUpUrl = photoUpUrl;
	}

	public String getPhotoDownUrl() {
		return this.photoDownUrl;
	}

	public void setPhotoDownUrl(String photoDownUrl) {
		this.photoDownUrl = photoDownUrl;
	}

	public String getPhotoInHandUrl() {
		return this.photoInHandUrl;
	}

	public void setPhotoInHandUrl(String photoInHandUrl) {
		this.photoInHandUrl = photoInHandUrl;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
